In [222]:
#importing necessary package
import pandas as pd
import numpy as np

In [223]:
dataset=pd.read_csv("Melbourne_housing.csv")
dataset.head()

Suburb             Address Rooms Type   Price Method        SellerG  \
0  Footscray    202/51 Gordon St     1    u   85000     PI        Burnham   
1  Caulfield          30 Pyne St     4    h  131000     PI         Rodney   
2     Coburg     171 Moreland Rd     4    h  145000     PI         Jellis   
3     Albion       8/6 Ridley St     1    u  145000     PI         Biggin   
4     Albion  10/117 Anderson Rd     1    u  185000      S  hockingstuart   

         Date Distance Week    CPI LastCPI Distance2  
0  03-09-2016      6.4   32  108.6   108.2       8.1  
1  25-02-2017      8.9   57  109.4   108.6      12.8  
2  04-06-2016      7.8   19  108.2   108.4       6.8  
3  28-05-2016     13.9   18  108.2   108.4      14.4  
4  22-08-2016     13.9   30  108.6   108.2      14.1

In [224]:
dataset.shape

(9383, 13)

In [225]:
dataset=dataset.drop(["Method",	"Distance","Week","CPI","LastCPI","Distance2","Address"], axis=1)
dataset.head()

Suburb Rooms Type   Price        SellerG        Date
0  Footscray     1    u   85000        Burnham  03-09-2016
1  Caulfield     4    h  131000         Rodney  25-02-2017
2     Coburg     4    h  145000         Jellis  04-06-2016
3     Albion     1    u  145000         Biggin  28-05-2016
4     Albion     1    u  185000  hockingstuart  22-08-2016

In [226]:
dataset.isnull().sum()

Suburb     0
Rooms      0
Type       0
Price      0
SellerG    0
Date       0
dtype: int64

In [227]:
dataset.duplicated().sum()

402

In [228]:
dataset.drop_duplicates(inplace=True)

In [229]:
dataset.duplicated().sum()

0

In [230]:
dataset.shape

(8981, 6)

In [231]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
dataset["Suburb"]=le.fit_transform(dataset["Suburb"])
dataset["Rooms"]=le.fit_transform(dataset["Rooms"])
dataset["Price"]=le.fit_transform(dataset["Price"])
dataset["Type"]=le.fit_transform(dataset["Type"])

In [232]:
x=dataset[["Suburb"	,"Rooms","Type"]]
y=dataset[["Price"]]

In [233]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [234]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()

In [235]:
model.fit(x_train,y_train)

LinearRegression()

In [236]:
model.score(x_test,y_test)
model.predict([[1,3,1]])


C:\Users\hp\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[801.69750874]])

In [237]:
#l1 regularization
from sklearn.linear_model import Lasso
lasso_reg=Lasso(alpha=1,max_iter=100,tol=0.1)
lasso_reg.fit(x_train,y_train)

Lasso(alpha=1, max_iter=100, tol=0.1)

In [238]:
lasso_reg.score(x_test,y_test)
lasso_reg.predict([[1,3,1]])

C:\Users\hp\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but Lasso was fitted with feature names
  warnings.warn(


array([802.37638527])

In [239]:
#l2 regularization
from sklearn.linear_model import Ridge
ridge_reg=Ridge(alpha=5,max_iter=100,tol=0.1)
ridge_reg.fit(x_train,y_train)

Ridge(alpha=5, max_iter=100, tol=0.1)

In [240]:
ridge_reg.score(x_test,y_test)
ridge_reg.predict([[1,3,1]])

C:\Users\hp\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(


array([[801.77319746]])

In [241]:
#l3 regularization
from sklearn.linear_model import ElasticNet

# Create an instance of Elastic Net regression model
elastic_net_reg = ElasticNet(alpha=1.0, l1_ratio=0.5) #. A l1_ratio of 0 corresponds to L2 regularization (Ridge), a l1_ratio of 1 corresponds to L1 regularization (Lasso),


In [242]:
elastic_net_reg.fit(x_train,y_train)

ElasticNet()

In [243]:
elastic_net_reg.score(x_test,y_test)

0.05748734961280366

In [244]:
elastic_net_reg.predict([[1,3,1]])

C:\Users\hp\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but ElasticNet was fitted with feature names
  warnings.warn(


array([829.23266509])